#include "cartoon.h"

#include "../../utils/io/io.h"
#include "../../utils/random/random.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>

char *Map(enum cartoon::type type) {
  char *result = nullptr;
  if (type == cartoon::DRAWING) {
    result = "DRAWING";
  } else if (type == cartoon::PUPPET) {
    result = "PUPPET";
  } else if (type == cartoon::PLASTICINE) {
    result = "PLASTICINE";
  }

  return result;
}

enum cartoon::type Map(char *type) {
  if (strcmp(type, "DRAWING") == 0) {
    return cartoon::DRAWING;
  } else if (strcmp(type, "PUPPET") == 0) {
    return cartoon::PUPPET;
  } else if (strcmp(type, "PLASTICINE") == 0) {
    return cartoon::PLASTICINE;
  } else {
    printf("Incorrect type of cartoon film given: %s", type);
    exit(1);
  }
}

enum cartoon::type Map(int typeNumber) {
  if (typeNumber == 1) {
    return cartoon::DRAWING;
  } else if (typeNumber == 2) {
    return cartoon::PUPPET;
  } else if (typeNumber == 3) {
    return cartoon::PLASTICINE;
  } else {
    printf("Incorrect type number of cartoon film generated by random: %d", typeNumber);
    exit(2);
  }
}

void In(cartoon &cartoon, FILE *file) {
  cartoon.title = ReadString(file);
  cartoon.year = ReadIntIn(file, 1970, 3022, "Incorrect year provided: expected a number between 1970, 3022");

  // Тип мультфильма в соответствии с названием перечисления внутри
  // структуры cartoon (@link cartoon.h)
  cartoon.type = Map(ReadString(file));
}

void inStochastic(cartoon &cartoon) {
  cartoon.title = RandomString(RandomInt(1, 51));
  cartoon.year = RandomInt(1970, 3022);

  // Тип мультфильма в соответствии с названием перечисления внутри
  // структуры cartoon (@link cartoon.h)
  cartoon.type = Map(RandomInt(1, 4));
}

void Out(cartoon &cartoon, FILE *output) {
  fprintf(output, "Cartoon{title=%s,year=%d,type=%s}", cartoon.title, cartoon.year, Map(cartoon.type));
}