#include "film.h"
#include "../utils/random/random.h"
#include "feature/feature.h"
#include "cartoon/cartoon.h"
#include "documentary/documentary.h"
#include "../utils/io/io.h"
#include <cstdio>
#include <cstring>
#include <cstdlib>

Film::Film(const char *title, int year) : title(title), year(year) {}

double Film::GetSortKey() {
  return 1.0 * year / double(strlen(title));
}

Film* Film::InStochastic() {
  // Номер жанра обобщенного фильма в соответствии с заданием
  int genre = RandomInt(1, 4);

  if (genre == 1) {
    // Игровой (feature) фильм
    return Feature::InStochastic();
  } else if (genre == 2) {
    // Мультфильм
    return Cartoon::InStochastic();
  } else if (genre == 3) {
    // Документальный фильм
    return Documentary::InStochastic();
  } else {
    printf("Wrong genre number of film generated by random: %d", genre);
    exit(2);
  }
}

Film* Film::In(FILE *file) {
  // Номер жанра обобщенного фильма в соответствии с заданием
  int genre = ReadIntIn(file, 1, 3, "Incorrect genre: excepted an integer in [1; 3]");
  const char *title = ReadString(file);
  int year = ReadIntIn(file, 1970, 3022, "Incorrect year: expected an integer in [1970; 3022]");

  if (genre == 1) {
    // Игровой (feature) фильм
    return Feature::In(title, year, file);
  } else if (genre == 2) {
    // Мультфильм
    return Cartoon::In(title, year, file);
  } else {
    // Документальный фильм
    return Documentary::In(title, year, file);
  }
}
