#include "film.h"
#include "../utils/random/random.h"
#include <cstdio>
#include <cstdlib>
#include <cstring>

void In(film &film, FILE *file) {
  // Номер жанра обобщенного фильма в соответствии с заданием
  int genre;
  fscanf(file, "%d", &genre);

  if (genre == 1) {
    // Игровой (feature) фильм
    film.genre = film::FEATURE;
    In(film.feature, file);
  } else if (genre == 2) {
    // Мультфильм
    film.genre = film::CARTOON;
    In(film.cartoon, file);
  } else if (genre == 3) {
    // Документальный фильм
    film.genre = film::DOCUMENTARY;
    In(film.documentary, file);
  } else {
    printf("Wrong genre number of film given: %d", genre);
    exit(1);
  }
}

void inStochastic(film &film) {
  // Номер жанра обобщенного фильма в соответствии с заданием
  int genre = RandomInt(1, 4);

  if (genre == 1) {
    // Игровой (feature) фильм
    film.genre = film::FEATURE;
    inStochastic(film.feature);
  } else if (genre == 2) {
    // Мультфильм
    film.genre = film::CARTOON;
    inStochastic(film.cartoon);
  } else if (genre == 3) {
    // Документальный фильм
    film.genre = film::DOCUMENTARY;
    inStochastic(film.documentary);
  } else {
    printf("Wrong genre number of film generated by random: %d", genre);
    exit(2);
  }
}

double YearOverTitleSymbols(film &film) {
  int year;
  char *title;

  if (film.genre == film::FEATURE) {
    year = film.feature.year;
    title = film.feature.title;
  } else if (film.genre == film::CARTOON) {
    year = film.cartoon.year;
    title = film.cartoon.title;
  } else if (film.genre == film::DOCUMENTARY) {
    year = film.documentary.year;
    title = film.documentary.title;
  } else {
    printf("Incorrect state: film genre is neither: FEATURE, CARTOON, DOCUMENTARY");
    exit(2);
  }

  return ((double) year) / strlen(title);
}