SECTION .rodata
drawing_string:  db "DRAWING", 0
puppet_string:  db "PUPPET", 0
plasticine_string:  db "PLASTICINE", 0
incorrect_cartoon:  db "Incorrect type of cartoon film given: ", 0
incorrect_genre_number:  db "Incorrect type number of cartoon film generated by random: ", 0
incorrect_year:  db "Incorrect year provided: expected a number between 1970 and 3022", 0
cartoon_out_head:  db "Cartoon{title=", 0
film_out_year:  db ",year=", 0
cartoon_out_type:  db ",type=", 0
film_out_tail:  db "}", 0
CONTAINER_MAX_SIZE: dd 10000
container_lack:  db "You have run out of container's capacity. Consider providing less entries", 0
container_stochastic_lack:  db "You have run out of container's capacity. Consider providing less entries", 0
film_out_pre:  db ". ", 0
film_out_sort_key:  db ", sort_key = ", 0
film_out_post:  db `\n`, 0
doc_incorrect_duration:  db "Incorrect duration provided: expected a number between 45, 3600", 0
documentary_out_head:  db "Documentary{title=", 0
documentary_out_duration:  db ",duration=", 0
feature_out_head:  db "Feature{title=", 0
feature_out_director:  db ",director=", 0
wrong_genre_provided:  db "Wrong genre", 0
wrong_genre_produced:  db "Wrong genre generated by random", 0
internal_genre_incorrect:  db "Incorrect state: film genre is neither FEATURE nor CARTOON nor DOCUMENTARY!", 0
done_reading:  db "Done reading..", 0
unexpected_eof:  db "Unexpected EOF", 0
incorrect_title:  db "Incorrect title give: expected a non-empty str", 0
alphabet:  db "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz0123456789", 0
incorrect_usage:  db `Incorrect usage.\n  Expected:\n     command -f input_file output_file_1 output_file_2\n  Or:\n     command -n size output_file_1 output_file_2\n`, 0
incorrect_qualifier:  db `Incorrect qualifier value.\n  Expected:\n     command -f input_file output_file_1 output_file_2\n  Or:\n     command -n size output_file_1 output_file_2\n`, 0
incorrect_size:  db `Incorrect size provided. Expected value < size <= 10'000\n`, 0
input_container_header:  db `Input container:\n`, 0
sorted_container_header:  db `Sorted container:\n`, 0
start_output:  db `Start\n`, 0
file_flag:  db "-f", 0
random_flag:  db "-n", 0
float_rounder:  dq 0.05
float_base:  dq 10.0
dump:
        dq 8000000000000000H
        dq 0000000000000000H

SECTION .bss

_edata:
__bss_start:
seed:
        resq    1

